Fix StoreKitService errors
Fixes the following errors:
- src/services/storeKitService.ts(26,17): error TS2339: Property 'Capacitor' does not exist on type 'Window & typeof globalThis'.
- src/services/storeKitService.ts(27,17): error TS2339: Property 'Capacitor' does not exist on type 'Window & typeof globalThis'.
- src/services/storeKitService.ts(48,48): error TS2307: Cannot find module '@capacitor-community/in-app-purchase' or its corresponding type declarations.
- src/services/storeKitService.ts(70,48): error TS2307: Cannot find module '@capacitor-community/in-app-purchase' or its corresponding type declarations.
- src/services/storeKitService.ts(96,48): error TS2307: Cannot find module '@capacitor-community/in-app-purchase' or its corresponding type declarations.
- src/services/storeKitService.ts(129,48): error TS2307: Cannot find module '@capacitor-community/in-app-purchase' or its corresponding type declarations.
- src/services/storeKitService.ts(158,48): error TS2307: Cannot find module '@capacitor-community/in-app-purchase' or its corresponding type declarations.